name: CI/CD Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Login Fly.io
      run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}
    - name: Build Docker image
      run: docker build -t usuario/mi-app:latest ./app
    - name: Push Docker image
      run: docker push usuario/mi-app:latest
    - name: Deploy with Fly.io
      run: flyctl deploy ./app
