name: CI/CD - Build & Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # para Workload Identity Federation
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (Workload Identity recommended)
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.ARTIFACT_REPO }}/fastapi:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.ARTIFACT_REPO }}/fastapi:${{ github.sha }} \
            --region ${REGION} --platform managed --allow-unauthenticated
